"""
renderer.py — Renders AI summary to terminal (Rich), markdown, or JSON
"""

import json
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.columns import Columns
from rich.text import Text
from rich.rule import Rule
from rich import box
from rich.markdown import Markdown
from io import StringIO

console = Console()


def render_summary(summary: dict, meta: dict, fmt: str = "terminal") -> str:
    if fmt == "json":
        return json.dumps({"meta": _meta_block(meta), "analysis": summary}, indent=2)
    elif fmt == "markdown":
        return _render_markdown(summary, meta)
    else:
        return _render_terminal(summary, meta)


def _meta_block(meta: dict) -> dict:
    return {
        "repo": meta["full_name"],
        "url": meta["url"],
        "stars": meta["stars"],
        "forks": meta["forks"],
        "language": meta["language"],
        "license": meta["license"],
        "last_updated": meta["updated_at"],
    }


def _render_terminal(summary: dict, meta: dict) -> str:
    """Render beautiful terminal output using Rich."""
    buf = StringIO()
    c = Console(file=buf, highlight=False)

    # Header
    stars = "⭐" * min(5, meta["stars"] // 1000 + 1) if meta["stars"] > 0 else ""
    c.print(Panel(
        f"[bold white]{meta['full_name']}[/bold white]  {stars}\n"
        f"[dim]{meta['url']}[/dim]\n\n"
        f"[bold yellow italic]\"{summary.get('one_liner', '')}\"[/bold yellow italic]",
        title="[cyan bold]📦 Repository Summary[/cyan bold]",
        border_style="cyan",
        padding=(1, 2),
    ))

    # Stats row
    stat_table = Table.grid(padding=(0, 3))
    stat_table.add_row(
        f"[green]★ {meta['stars']:,}[/green] stars",
        f"[blue]⑂ {meta['forks']:,}[/blue] forks",
        f"[yellow]⚠ {meta['open_issues']:,}[/yellow] issues",
        f"[magenta]📄 {meta['license']}[/magenta]",
        f"[dim]Updated {meta['updated_at']}[/dim]",
    )
    c.print(stat_table)
    c.print()

    # What it does
    c.print(Rule("[bold]🎯 What It Does[/bold]", style="cyan"))
    c.print(f"  {summary.get('what_it_does', 'N/A')}\n")

    # Tech stack
    c.print(Rule("[bold]🛠 Tech Stack[/bold]", style="cyan"))
    stack = summary.get("tech_stack", [])
    if stack:
        tags = "  " + "  ".join(f"[bold cyan on grey15] {t} [/bold cyan on grey15]" for t in stack)
        c.print(tags)
    c.print()

    # Install steps
    c.print(Rule("[bold]📥 How to Install[/bold]", style="cyan"))
    steps = summary.get("how_to_install", [])
    for i, step in enumerate(steps, 1):
        c.print(f"  [dim]{i}.[/dim] {step}")
    c.print()

    # Usage
    c.print(Rule("[bold]🚀 How to Use[/bold]", style="cyan"))
    usage = summary.get("how_to_use", "")
    if "```" in usage or any(c in usage for c in ["$", "python", "npm", "node", "cargo", "go run"]):
        c.print(Panel(usage, border_style="dim green", padding=(0, 2)))
    else:
        c.print(f"  {usage}")
    c.print()

    # Key files table
    c.print(Rule("[bold]📁 Key Files[/bold]", style="cyan"))
    key_files = summary.get("key_files", [])
    if key_files:
        ftable = Table(box=box.SIMPLE, show_header=True, header_style="bold dim")
        ftable.add_column("File", style="bold cyan", no_wrap=True)
        ftable.add_column("Purpose", style="white")
        for kf in key_files:
            ftable.add_row(kf.get("file", ""), kf.get("purpose", ""))
        c.print(ftable)

    # Architecture
    arch = summary.get("architecture_overview", "")
    if arch:
        c.print(Rule("[bold]🏗 Architecture[/bold]", style="cyan"))
        c.print(f"  {arch}\n")

    # Good first contribution
    gfc = summary.get("good_first_contribution", "")
    if gfc:
        c.print(Panel(
            f"[bold green]💡 Good First Contribution[/bold green]\n\n{gfc}",
            border_style="green",
            padding=(0, 2),
        ))

    # Caveats
    caveats = summary.get("caveats", "")
    if caveats and caveats.lower() not in ("none", "n/a", ""):
        c.print(Panel(
            f"[bold yellow]⚠️  Caveats[/bold yellow]\n\n{caveats}",
            border_style="yellow",
            padding=(0, 2),
        ))

    # Footer
    c.print()
    c.print(f"[dim]Generated by [bold]RepoWise[/bold] · github.com/YOUR_USERNAME/repowise[/dim]")
    c.print()

    return buf.getvalue()


def _render_markdown(summary: dict, meta: dict) -> str:
    """Render clean Markdown output (great for saving/sharing)."""
    lines = []

    lines.append(f"# 🔍 RepoWise Summary: `{meta['full_name']}`")
    lines.append(f"\n> {summary.get('one_liner', '')}")
    lines.append(f"\n**URL:** {meta['url']}  ")
    lines.append(f"**Stars:** ⭐ {meta['stars']:,} | **Forks:** {meta['forks']:,} | **Issues:** {meta['open_issues']:,}  ")
    lines.append(f"**License:** {meta['license']} | **Language:** {meta['language']} | **Updated:** {meta['updated_at']}")

    lines.append(f"\n---\n\n## 🎯 What It Does\n\n{summary.get('what_it_does', 'N/A')}")

    stack = summary.get("tech_stack", [])
    if stack:
        lines.append("\n## 🛠 Tech Stack\n")
        lines.append(" ".join(f"`{t}`" for t in stack))

    lines.append("\n## 📥 How to Install\n")
    for i, step in enumerate(summary.get("how_to_install", []), 1):
        lines.append(f"{i}. {step}")

    usage = summary.get("how_to_use", "")
    if usage:
        lines.append(f"\n## 🚀 How to Use\n\n{usage}")

    key_files = summary.get("key_files", [])
    if key_files:
        lines.append("\n## 📁 Key Files\n")
        lines.append("| File | Purpose |")
        lines.append("|------|---------|")
        for kf in key_files:
            lines.append(f"| `{kf.get('file', '')}` | {kf.get('purpose', '')} |")

    arch = summary.get("architecture_overview", "")
    if arch:
        lines.append(f"\n## 🏗 Architecture\n\n{arch}")

    gfc = summary.get("good_first_contribution", "")
    if gfc:
        lines.append(f"\n## 💡 Good First Contribution\n\n{gfc}")

    caveats = summary.get("caveats", "")
    if caveats and caveats.lower() not in ("none", "n/a", ""):
        lines.append(f"\n## ⚠️ Caveats\n\n{caveats}")

    lines.append("\n---\n\n*Generated by [RepoWise](https://github.com/YOUR_USERNAME/repowise)*")

    return "\n".join(lines)
